#!/bin/sh

/sbin/rpcbind
/usr/sbin/rpc.nfsd --debug 8 --no-udp --no-nfs-version 2 --no-nfs-version 3
/usr/sbin/exportfs -ra
/usr/sbin/rpc.mountd --foreground --debug all --no-udp --no-nfs-version 2 --no-nfs-version 3
