#!/bin/sh

echo "/shared/ro $IP/$MASK(ro,async,no_subtree_check)" > /etc/exports
echo "/shared/rw $IP/$MASK(rw,async,no_subtree_check)" >> /etc/exports

/sbin/rpcbind
/usr/sbin/rpc.nfsd --debug 8 --no-udp --no-nfs-version 2 --no-nfs-version 3
/usr/sbin/exportfs -ra
/usr/sbin/rpc.mountd --foreground --debug all --no-udp --no-nfs-version 2 --no-nfs-version 3
